In [21]:
!pip install wordllama

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.7/17.7 MB 53.6 MB/s eta 0:00:00:00:0100:01


In [22]:
from wordllama import WordLlama

# Load the default WordLlama model
wl = WordLlama.load(trunc_dim=64)

In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

import numpy as np

import datetime

import warnings
warnings.filterwarnings('ignore')

In [2]:
video_data = pd.read_parquet('/kaggle/input/ohrenet-data-set-na-30-gb/video_stat.parquet')

In [3]:
video_data = video_data[~(video_data.title == "")]

In [4]:
drop_columns = ['v_is_hidden', 'v_is_deleted', 
                'v_frac_avg_watchtime_1_day_duration', 
                'v_frac_avg_watchtime_7_day_duration', 
                'v_frac_avg_watchtime_30_day_duration', 'row_number']
video_data.drop(columns = drop_columns, inplace=True)

In [5]:
video_data.reset_index(drop=True, inplace=True)

In [6]:
video_data['v_pub_datetime'] = pd.to_datetime(video_data['v_pub_datetime'])

In [16]:
video_data['v_pub_datetime'] = video_data['v_pub_datetime'].astype(str)

In [11]:
video_data['v_pub_datetime'] = video_data['v_pub_datetime'].apply(lambda x: x.timestamp())

In [17]:
video_data_dict = video_data[['video_id', 'v_pub_datetime', 'title', 'description', 'category_id']].set_index('video_id').T.to_dict('list')

In [19]:
import pickle 

with open('video_data_dict.pkl', 'wb') as f:
    pickle.dump(video_data_dict, f)

In [13]:
((video_data.groupby('category_id').count()[['video_id']]/len(video_data)) * 100).sort_values('video_id')

video_id
category_id                            
Дизайн                         0.174059
Аудио                          0.187048
Недвижимость                   0.191356
Природа                        0.282790
Наука                          0.397629
Психология                     0.401809
Охота и рыбалка                0.414669
Аудиокниги                     0.445211
Бизнес и предпринимательство   0.473889
Красота                        0.520570
Сад и огород                   0.573167
UNKNOWN                        0.663830
Аниме                          0.680805
Строительство и ремонт         0.703181
Обзоры и распаковки товаров    0.736360
Культура                       0.763494
Животные                       0.775197
Лайфхаки                       0.779955
Здоровье                       0.816734
Эзотерика                      0.921800
Путешествия                    1.080042
Технологии и интернет          1.225294
Хобби                          1.278020
Интервью                       1.364439
Техника и оборудование         1.370419
Спорт                          1.843986
Мультфильмы                    1.850930
Еда                            2.073407
Юмор                           2.459848
Авто-мото                      2.592370
Детям                          3.111525
Обучение                       3.114033
Лайфстайл                      3.238196
Фильмы                         3.878685
Развлечения                    4.958919
Музыка                         4.993834
Видеоигры                      5.572273
Телепередачи                   6.100302
Сериалы                        6.175533
Разное                        30.814394

In [14]:
video_data.isna().sum()

video_id                                 0
v_pub_datetime                           0
v_total_comments                         0
v_year_views                             0
v_month_views                            0
v_week_views                             0
v_day_views                              0
v_likes                                  0
v_dislikes                               0
v_duration                               0
v_cr_click_like_7_days                   0
v_cr_click_dislike_7_days                0
v_cr_click_vtop_7_days                   0
v_cr_click_long_view_7_days              0
v_cr_click_comment_7_days                0
v_cr_click_like_30_days                  0
v_cr_click_dislike_30_days               0
v_cr_click_vtop_30_days                  0
v_cr_click_long_view_30_days             0
v_cr_click_comment_30_days               0
v_cr_click_like_1_days                   0
v_cr_click_dislike_1_days                0
v_cr_click_vtop_1_days                   0
v_cr_click_

In [17]:
category_id_embeds = wl.embed(list(video_data['category_id'].values))

In [18]:
title_embeds = wl.embed(list(video_data['title'].values))

In [19]:
description_embeds = wl.embed(list(video_data['description'].values))

In [26]:
video_embeds = category_id_embeds + title_embeds*0.5 + description_embeds*0.5

In [27]:
video_embeds

array([[-0.5831768 ,  0.28563842,  0.275738  , ...,  0.17058557,
        -0.06529325, -0.338973  ],
       [-0.664851  ,  0.7072224 ,  0.00805275, ..., -0.17414491,
        -0.05017198, -0.23635134],
       [-0.79016507,  0.31092542, -0.65970737, ..., -0.14822435,
        -0.0459419 , -1.1075921 ],
       ...,
       [-0.52784103,  0.7532077 ,  0.30392748, ..., -0.59711385,
         0.20593771, -0.7534518 ],
       [ 0.03709494,  0.36053303, -0.32807246, ..., -0.07837309,
         0.36607343, -0.52025425],
       [-0.23801419,  0.5977721 , -0.27375567, ..., -0.13478799,
         0.26058307, -0.5754348 ]], dtype=float32)

In [28]:
stats_vecs = video_data.iloc[:, 1:-4].values

In [29]:
stats_vecs

array([[1.71848148e+09, 0.00000000e+00, 5.56000000e+02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.61875606e+09, 0.00000000e+00, 1.09000000e+02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.66869220e+09, 0.00000000e+00, 1.63000000e+02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.66771590e+09, 0.00000000e+00, 1.62000000e+02, ...,
        0.00000000e+00, 0.00000000e+00, 9.00000000e+00],
       [1.70017413e+09, 0.00000000e+00, 1.44000000e+02, ...,
        0.00000000e+00, 2.00000000e+00, 8.00000000e+00],
       [1.70024604e+09, 0.00000000e+00, 2.51000000e+03, ...,
        0.00000000e+00, 4.90000000e+01, 1.53000000e+02]])

In [30]:
video_embeds = np.concatenate((video_embeds, stats_vecs), axis=1)

In [31]:
video_embeds

array([[-5.83176792e-01,  2.85638422e-01,  2.75738001e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.64851010e-01,  7.07222402e-01,  8.05275328e-03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-7.90165067e-01,  3.10925424e-01, -6.59707367e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [-5.27841032e-01,  7.53207684e-01,  3.03927481e-01, ...,
         0.00000000e+00,  0.00000000e+00,  9.00000000e+00],
       [ 3.70949432e-02,  3.60533029e-01, -3.28072459e-01, ...,
         0.00000000e+00,  2.00000000e+00,  8.00000000e+00],
       [-2.38014191e-01,  5.97772121e-01, -2.73755670e-01, ...,
         0.00000000e+00,  4.90000000e+01,  1.53000000e+02]])

72 столбец это v_duration

In [32]:
pd.DataFrame(video_embeds)

0         1         2         3         4         5         6   \
0       -0.583177  0.285638  0.275738 -0.121871  0.564524 -0.365153  0.362858   
1       -0.664851  0.707222  0.008053 -0.751596  0.373044 -0.562850 -0.102521   
2       -0.790165  0.310925 -0.659707 -0.643019  0.406513  0.042416  0.208823   
3       -1.801291  0.815261 -0.024182 -0.223238  0.202299 -0.440562  0.153128   
4       -0.051967  0.315467 -0.382886 -0.416392  0.510738 -0.441189 -0.089106   
...           ...       ...       ...       ...       ...       ...       ...   
1555213 -0.617720  0.739599  0.576742 -0.599602 -0.115528 -0.379457 -0.514471   
1555214  0.511209 -0.140758  0.924966  0.194347  0.247384 -0.693325  0.354614   
1555215 -0.527841  0.753208  0.303927 -0.508716  0.018977 -0.792114  0.053869   
1555216  0.037095  0.360533 -0.328072 -0.475727  0.593304 -0.608588 -0.109556   
1555217 -0.238014  0.597772 -0.273756 -0.491982  0.624434 -0.765379  0.040062   

               7         8         9         10        11        12        13  \
0       -0.751143  0.385155  0.538049  0.645825 -0.004905  0.729265  0.495231   
1       -0.893505  0.395862 -0.162864  0.521615 -0.220767 -0.031076  0.137717   
2       -0.862269 -0.328970  0.692598 -0.065213 -0.709210  0.059631  0.507024   
3       -0.455030  0.294274  0.594064  0.357509 -0.709632 -0.038351  0.562807   
4       -0.616665 -0.140649 -0.422775  0.052300 -0.011423  0.376656 -0.021345   
...           ...       ...       ...       ...       ...       ...       ...   
1555213 -0.463430  0.005150  0.402246 -0.016639 -0.277346  0.298808  0.327802   
1555214 -0.342760 -0.506073  0.161464 -0.869040 -0.336718 -0.391929  0.229303   
1555215 -0.271284 -0.014065  0.400296  0.392383 -1.108979 -0.183581  0.574028   
1555216 -0.532786 -0.096178 -0.265313  0.033344 -0.059156  0.341477 -0.032362   
1555217 -0.706679 -0.031483 -0.317654 -0.037565 -0.040593  0.433324  0.007204   

               14        15        16        17        18        19        20  \
0        0.119218  0.053123 -0.218398  0.742045 -0.290449  0.172615  0.067378   
1       -0.925609 -0.214496  0.180183  0.943128  0.022646 -0.183280 -0.269995   
2        0.871917 -0.364344  0.104277  1.018446 -0.230907 -1.150446 -0.007015   
3       -0.166207 -0.168631 -0.060880  1.022655  0.124486 -0.716810 -0.548097   
4       -0.877051 -0.444594 -0.489612  1.101015 -0.389657  0.127566 -0.720832   
...           ...       ...       ...       ...       ...       ...       ...   
1555213 -0.206710 -0.166611  0.662547  1.230577  0.504531  0.117258 -0.607662   
1555214  0.311151 -0.574097  0.360914  0.307853 -0.447272 -0.374193  0.533748   
1555215  0.079619 -0.295418  0.453098  1.033440 -0.067341 -0.106814 -0.164619   
1555216 -0.898788 -0.605243 -0.474083  1.157251 -0.397449 -0.035315 -0.693299   
1555217 -0.747186 -0.539240 -0.389205  1.269728 -0.489793  0.149367 -0.880361   

               21        22        23        24        25        26        27  \
0       -0.789981  0.600600 -0.104020 -0.323671  0.085661  0.100123  0.507746   
1       -0.034704  0.854077  0.251240 -0.297983  0.152702  0.608045 -0.354415   
2       -0.109687  0.543142  0.675645  0.784227  0.594423  0.333407 -1.104720   
3        0.014735 -0.042354  0.181423 -0.103773  1.087313 -0.090668  0.269261   
4        0.400770  0.709844 -0.386637 -0.131038  0.207414  0.838347 -1.059825   
...           ...       ...       ...       ...       ...       ...       ...   
1555213 -0.271876  0.403956 -0.445593  0.646314  0.532850  0.269062 -0.230427   
1555214 -0.292925 -0.178650 -0.490246  0.555127  0.038050  0.039904 -0.518934   
1555215 -0.695199  0.384993 -0.125999 -0.389207  0.916325 -0.290060  0.297316   
1555216  0.324896  0.885704 -0.290456 -0.057918  0.310831  1.047164 -1.179448   
1555217  0.233628  0.923272 -0.170145 -0.195406  0.314750  1.194652 -1.105142   

               28        29        30        31        32        33        34  \
0        0.179764  0.051270  0.834238 -0.2

In [33]:
result_video_embeds = pd.concat([video_data['video_id'],pd.DataFrame(video_embeds)], axis=1)

In [34]:
result_video_embeds.to_orc('result_video_embeds_all.orc')